"""meme table

Revision ID: 35db38022620
Revises: 
Create Date: 2019-11-05 22:21:59.424306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35db38022620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('caption', sa.String(length=2000), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('num_contests', sa.Integer(), nullable=True),
    sa.Column('num_no_meme_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meme_filename'), 'meme', ['filename'], unique=True)
    op.create_index(op.f('ix_meme_num_contests'), 'meme', ['num_contests'], unique=False)
    op.create_index(op.f('ix_meme_num_no_meme_votes'), 'meme', ['num_no_meme_votes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meme_num_no_meme_votes'), table_name='meme')
    op.drop_index(op.f('ix_meme_num_contests'), table_name='meme')
    op.drop_index(op.f('ix_meme_filename'), table_name='meme')
    op.drop_table('meme')
    # ### end Alembic commands ###
